apiVersion: v1
kind: Service
metadata:
  name: hello-world-service
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: hello-world
  ports:
  - protocol: TCP
    port: {{ .Values.service_port }}
    targetPort: {{ .Values.container_port }}